image: 'Visual Studio 2019'

platform:
  - 'x64'
  - 'x86'

configuration:
  - 'Debug'
  - 'Release'

environment:
  PATH: 'C:\Program Files\OpenCppCoverage;C:\Python34;C:\Python34\Scripts;%PATH%'
  DEPENDENCIES_FOLDER: 'C:\projects\dependencies'
  DOWNLOADS_FOLDER: 'C:\projects\downloads'
  BUILD_HOME: '%APPVEYOR_BUILD_FOLDER%\build'
  COVERAGE_WORK_FOLDER: '%APPVEYOR_BUILD_FOLDER%\build\coverage'
  COBERTURA_COVERAGE_FILE: '%APPVEYOR_BUILD_FOLDER%\build\coverage\coverage.xml'
  VSWHERE_URL: 'https://github.com/Microsoft/vswhere/releases/download'
  VSWHERE_VERSION: '2.8.4'
  VSWHERE_DIST_NAME: 'vswhere.exe'
  COVERAGE_BUILD_CANDIDATE: '0'
  COVERAGE_ARTIFACT_NAME: 'coverage'
  CURL_CONNECT_TIMEOUT: '300'
  CURL_MAX_TIME: '1800'
  CURL_RETRY: '10'
  CURL_RETRY_DELAY: '10'
  PIP_RETRY: '10'
  CODECOV_VERSION: '2.0.15'

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2019'
      TOOLCHAIN: 'msvc'
      MSVC_VERSION: '14.2'
      RUNTIME_LINKAGE: 'static'
    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2017'
      TOOLCHAIN: 'msvc'
      MSVC_VERSION: '14.1'
      RUNTIME_LINKAGE: 'static'
    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      TOOLCHAIN: 'msvc'
      MSVC_VERSION: '14.0'
      RUNTIME_LINKAGE: 'static'
      COVERAGE_BUILD_CANDIDATE: '1'
    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      TOOLCHAIN: 'mingw'
      MINGW_VERSION: '8.1.0'
      MINGW_RT_VERSION: '6'
      MINGW_REVISION: '0'
      RUNTIME_LINKAGE: 'static'
    - APPVEYOR_BUILD_WORKER_IMAGE: 'Visual Studio 2015'
      TOOLCHAIN: 'mingw'
      MINGW_VERSION: '7.3.0'
      MINGW_RT_VERSION: '5'
      MINGW_REVISION: '0'
      RUNTIME_LINKAGE: 'static'

matrix:
  exclude:
    - platform: 'x86'
      TOOLCHAIN: 'mingw'

cache:
  - 'C:\projects\downloads -> .appveyor.yml'

install:
  - ps: '.\scripts\appveyor\install.ps1'
  - cmd: 'if not "%WINDOWS_SDK_ENV_BATCH_FILE%"=="" call "%WINDOWS_SDK_ENV_BATCH_FILE%" %WINDOWS_SDK_ENV_PARAMETERS%'
  - cmd: 'if not "%MSVC_VARS_BATCH_FILE%"=="" call "%MSVC_VARS_BATCH_FILE%" %MSVC_VARS_PLATFORM%'
  - ps: '.\scripts\appveyor\environment.ps1'

build_script:
  - ps: '.\scripts\appveyor\build.ps1'

test_script:
  - ps: '.\scripts\appveyor\test.ps1'

artifacts:
  - path: 'build\src\brackets$(ARTIFACT_PATH_SUFFIX)*.exe'
    name: 'brackets'
  - path: 'build\src\top$(ARTIFACT_PATH_SUFFIX)*.exe'
    name: 'top'
  - path: 'build\src\rle$(ARTIFACT_PATH_SUFFIX)*.exe'
    name: 'rle'
  - path: 'build\src\stone_jewellery$(ARTIFACT_PATH_SUFFIX)*.exe'
    name: 'stone_jewellery'
  - path: 'build\tests\top_test$(ARTIFACT_PATH_SUFFIX)*.exe'
    name: 'top_test'
  - path: 'build\tests\brackets_test$(ARTIFACT_PATH_SUFFIX)*.exe'
    name: 'brackets_test'
  - path: 'build\tests\rle_test$(ARTIFACT_PATH_SUFFIX)*.exe'
    name: 'rle_test'
  - path: 'build\tests\stone_jewellery_test$(ARTIFACT_PATH_SUFFIX)*.exe'
    name: 'stone_jewellery_test'
