codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  max_report_age: off
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        if_no_uploads: error
    patch:
      default:
        if_no_uploads: error
    changes: true

ignore:
  - "cmake/*"
  - "extern/*"
  - "scripts/*"
  - "src/main/*"
  - "tests/*"

comment:
  layout: "header, diff, changes, suggestions"
  behavior: default
